# Generated by Django 3.2.7 on 2021-09-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_scope_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tabel',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статей'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статей'},
        ),
        migrations.AlterField(
            model_name='scope',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
    ]
